//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService.HQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HQServiceReference.IHQService")]
    public interface IHQService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/requestStockHQ", ReplyAction="http://tempuri.org/IHQService/requestStockHQResponse")]
        int requestStockHQ(int proposedOrderId, string branch, int productId, int quantityAsked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/acceptStockRequest", ReplyAction="http://tempuri.org/IHQService/acceptStockRequestResponse")]
        int acceptStockRequest(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/logLocalOrder", ReplyAction="http://tempuri.org/IHQService/logLocalOrderResponse")]
        bool logLocalOrder(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHQServiceChannel : ProductService.HQServiceReference.IHQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQServiceClient : System.ServiceModel.ClientBase<ProductService.HQServiceReference.IHQService>, ProductService.HQServiceReference.IHQService {
        
        public HQServiceClient() {
        }
        
        public HQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int requestStockHQ(int proposedOrderId, string branch, int productId, int quantityAsked) {
            return base.Channel.requestStockHQ(proposedOrderId, branch, productId, quantityAsked);
        }
        
        public int acceptStockRequest(int orderId) {
            return base.Channel.acceptStockRequest(orderId);
        }
        
        public bool logLocalOrder(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted) {
            return base.Channel.logLocalOrder(orderId, localClientId, productId, date, quantity, localShipperId, isAccepted);
        }
    }
}
