//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductService.HQServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HQServiceReference.IHQService")]
    public interface IHQService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/GetData", ReplyAction="http://tempuri.org/IHQService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IHQService/GetDataUsingDataContractResponse")]
        ProductService.HQServiceReference.CompositeType GetDataUsingDataContract(ProductService.HQServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/CheckInsertIsDone", ReplyAction="http://tempuri.org/IHQService/CheckInsertIsDoneResponse")]
        bool CheckInsertIsDone(int _id, string _name, string _type, int _quant, int _price, int _cost);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/CheckUpdateProductIsDone", ReplyAction="http://tempuri.org/IHQService/CheckUpdateProductIsDoneResponse")]
        bool CheckUpdateProductIsDone(int _id, int new_quant, int new_price, int new_cost);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHQServiceChannel : ProductService.HQServiceReference.IHQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQServiceClient : System.ServiceModel.ClientBase<ProductService.HQServiceReference.IHQService>, ProductService.HQServiceReference.IHQService {
        
        public HQServiceClient() {
        }
        
        public HQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public ProductService.HQServiceReference.CompositeType GetDataUsingDataContract(ProductService.HQServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public bool CheckInsertIsDone(int _id, string _name, string _type, int _quant, int _price, int _cost) {
            return base.Channel.CheckInsertIsDone(_id, _name, _type, _quant, _price, _cost);
        }
        
        public bool CheckUpdateProductIsDone(int _id, int new_quant, int new_price, int new_cost) {
            return base.Channel.CheckUpdateProductIsDone(_id, new_quant, new_price, new_cost);
        }
    }
}
