//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateService.HQServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductStockDTO", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class ProductStockDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PendingStockOrderDTO", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class PendingStockOrderDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityAskedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int QuantityAsked {
            get {
                return this.QuantityAskedField;
            }
            set {
                if ((this.QuantityAskedField.Equals(value) != true)) {
                    this.QuantityAskedField = value;
                    this.RaisePropertyChanged("QuantityAsked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                if ((object.ReferenceEquals(this.branchField, value) != true)) {
                    this.branchField = value;
                    this.RaisePropertyChanged("branch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchDTO", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class BranchDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrdersLogDTO", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class OrdersLogDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocalClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocalShipperIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Accepted {
            get {
                return this.AcceptedField;
            }
            set {
                if ((this.AcceptedField.Equals(value) != true)) {
                    this.AcceptedField = value;
                    this.RaisePropertyChanged("Accepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocalClientID {
            get {
                return this.LocalClientIDField;
            }
            set {
                if ((this.LocalClientIDField.Equals(value) != true)) {
                    this.LocalClientIDField = value;
                    this.RaisePropertyChanged("LocalClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocalShipperID {
            get {
                return this.LocalShipperIDField;
            }
            set {
                if ((this.LocalShipperIDField.Equals(value) != true)) {
                    this.LocalShipperIDField = value;
                    this.RaisePropertyChanged("LocalShipperID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((this.OrderIDField.Equals(value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockOrderLogDTO", Namespace="http://schemas.datacontract.org/2004/07/HQService")]
    [System.SerializableAttribute()]
    public partial class StockOrderLogDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branchField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string branch {
            get {
                return this.branchField;
            }
            set {
                if ((object.ReferenceEquals(this.branchField, value) != true)) {
                    this.branchField = value;
                    this.RaisePropertyChanged("branch");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HQServiceReference.IHQService")]
    public interface IHQService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/requestStockHQ", ReplyAction="http://tempuri.org/IHQService/requestStockHQResponse")]
        int requestStockHQ(int proposedOrderId, string branch, int productId, int quantityAsked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/acceptStockRequest", ReplyAction="http://tempuri.org/IHQService/acceptStockRequestResponse")]
        int acceptStockRequest(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/logLocalOrder", ReplyAction="http://tempuri.org/IHQService/logLocalOrderResponse")]
        bool logLocalOrder(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted, string justification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/dismissStockOrder", ReplyAction="http://tempuri.org/IHQService/dismissStockOrderResponse")]
        bool dismissStockOrder(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/getProductStocks", ReplyAction="http://tempuri.org/IHQService/getProductStocksResponse")]
        UpdateService.HQServiceReference.ProductStockDTO[] getProductStocks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/getPendingStockOrders", ReplyAction="http://tempuri.org/IHQService/getPendingStockOrdersResponse")]
        UpdateService.HQServiceReference.PendingStockOrderDTO[] getPendingStockOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/getBranches", ReplyAction="http://tempuri.org/IHQService/getBranchesResponse")]
        UpdateService.HQServiceReference.BranchDTO[] getBranches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/getOrdersLogs", ReplyAction="http://tempuri.org/IHQService/getOrdersLogsResponse")]
        UpdateService.HQServiceReference.OrdersLogDTO[] getOrdersLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/getStockOrderLogs", ReplyAction="http://tempuri.org/IHQService/getStockOrderLogsResponse")]
        UpdateService.HQServiceReference.StockOrderLogDTO[] getStockOrderLogs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/updateBranchStock", ReplyAction="http://tempuri.org/IHQService/updateBranchStockResponse")]
        void updateBranchStock(int[] productsStock);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHQServiceChannel : UpdateService.HQServiceReference.IHQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQServiceClient : System.ServiceModel.ClientBase<UpdateService.HQServiceReference.IHQService>, UpdateService.HQServiceReference.IHQService {
        
        public HQServiceClient() {
        }
        
        public HQServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HQServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int requestStockHQ(int proposedOrderId, string branch, int productId, int quantityAsked) {
            return base.Channel.requestStockHQ(proposedOrderId, branch, productId, quantityAsked);
        }
        
        public int acceptStockRequest(int orderId) {
            return base.Channel.acceptStockRequest(orderId);
        }
        
        public bool logLocalOrder(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted, string justification) {
            return base.Channel.logLocalOrder(orderId, localClientId, productId, date, quantity, localShipperId, isAccepted, justification);
        }
        
        public bool dismissStockOrder(int orderId) {
            return base.Channel.dismissStockOrder(orderId);
        }
        
        public UpdateService.HQServiceReference.ProductStockDTO[] getProductStocks() {
            return base.Channel.getProductStocks();
        }
        
        public UpdateService.HQServiceReference.PendingStockOrderDTO[] getPendingStockOrders() {
            return base.Channel.getPendingStockOrders();
        }
        
        public UpdateService.HQServiceReference.BranchDTO[] getBranches() {
            return base.Channel.getBranches();
        }
        
        public UpdateService.HQServiceReference.OrdersLogDTO[] getOrdersLogs() {
            return base.Channel.getOrdersLogs();
        }
        
        public UpdateService.HQServiceReference.StockOrderLogDTO[] getStockOrderLogs() {
            return base.Channel.getStockOrderLogs();
        }
        
        public void updateBranchStock(int[] productsStock) {
            base.Channel.updateBranchStock(productsStock);
        }
    }
}
