//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersLog
    {
        public int OrderID { get; set; }
        public int LocalClientID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public int LocalShipperID { get; set; }
        public short Accepted { get; set; }
    }
}
