//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HQService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingStockOrders
    {
        public int OrderID { get; set; }
        public string branch { get; set; }
        public int ProductID { get; set; }
        public int QuantityAsked { get; set; }
    }
}
