//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26720.2
// 
namespace LocalAdminApp.HQServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HQServiceReference.IHQService")]
    public interface IHQService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/requestStockHQ", ReplyAction="http://tempuri.org/IHQService/requestStockHQResponse")]
        System.Threading.Tasks.Task<int> requestStockHQAsync(int proposedOrderId, string branch, int productId, int quantityAsked);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/acceptStockRequest", ReplyAction="http://tempuri.org/IHQService/acceptStockRequestResponse")]
        System.Threading.Tasks.Task<int> acceptStockRequestAsync(int orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHQService/logLocalOrder", ReplyAction="http://tempuri.org/IHQService/logLocalOrderResponse")]
        System.Threading.Tasks.Task<bool> logLocalOrderAsync(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHQServiceChannel : LocalAdminApp.HQServiceReference.IHQService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HQServiceClient : System.ServiceModel.ClientBase<LocalAdminApp.HQServiceReference.IHQService>, LocalAdminApp.HQServiceReference.IHQService {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public HQServiceClient() : 
                base(HQServiceClient.GetDefaultBinding(), HQServiceClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IHQService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HQServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(HQServiceClient.GetBindingForEndpoint(endpointConfiguration), HQServiceClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HQServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(HQServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HQServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(HQServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public HQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task<int> requestStockHQAsync(int proposedOrderId, string branch, int productId, int quantityAsked) {
            return base.Channel.requestStockHQAsync(proposedOrderId, branch, productId, quantityAsked);
        }
        
        public System.Threading.Tasks.Task<int> acceptStockRequestAsync(int orderId) {
            return base.Channel.acceptStockRequestAsync(orderId);
        }
        
        public System.Threading.Tasks.Task<bool> logLocalOrderAsync(int orderId, int localClientId, int productId, string date, int quantity, int localShipperId, bool isAccepted) {
            return base.Channel.logLocalOrderAsync(orderId, localClientId, productId, date, quantity, localShipperId, isAccepted);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHQService)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IHQService)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/HQService/HQServiceClass/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return HQServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IHQService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return HQServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IHQService);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IHQService,
        }
    }
}
